=== OParl/spec/schema/Body.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/Body",
    "title": "Body",
    "description": "{{ Body.description }}",
    "type": "object",
    "required": [
        "id",
        "type",
        "name",
        "organization",
        "person",
        "meeting",
        "paper",
        "legislativeTerm"
    ],
    "properties": {
        "id": {
            "type": "string",
            "format": "url"
        },
        "type": {
            "type": "string",
            "const": "https://schema.oparl.org/1.1/Body"
        },
        "system": {
            "description": "{{ Body.properties.system.description }}",
            "references": "System",
            "backreference": "bodies",
            "cardinality": "n:1",
            "type": "string",
            "format": "url"
        },
        "shortName": {
            "description": "{{ Body.properties.shortName.description }}",
            "type": "string"
        },
        "name": {
            "description": "{{ Body.properties.name.description }}",
            "type": "string"
        },
        "website": {
            "description": "{{ Body.properties.website.description }}",
            "type": "string",
            "format": "url"
        },
        "license": {
            "description": "{{ Body.properties.license.description }}",
            "type": "string",
            "format": "url"
        },
        "licenseValidSince": {
            "description": "{{ Body.properties.licenseValidSince.description }}",
            "type": "string",
            "format": "date-time"
        },
        "oparlSince": {
            "description": "{{ Body.properties.oparlSince.description }}",
            "type": "string",
            "format": "date-time"
        },
        "ags": {
            "description": "{{ Body.properties.ags.description }}",
            "type": "string"
        },
        "rgs": {
            "description": "{{ Body.properties.rgs.description }}",
            "type": "string"
        },
        "equivalent": {
            "description": "{{ Body.properties.equivalent.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url"
            }
        },
        "contactEmail": {
            "description": "{{ Body.properties.contactEmail.description }}",
            "type": "string"
        },
        "contactName": {
            "description": "{{ Body.properties.contactName.description }}",
            "type": "string"
        },
        "organization": {
            "description": "{{ Body.properties.organization.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Organization.json"
            }
        },
        "person": {
            "description": "{{ Body.properties.person.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Person.json"
            }
        },
        "meeting": {
            "description": "{{ Body.properties.meeting.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Meeting.json"
            }
        },
        "paper": {
            "description": "{{ Body.properties.paper.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Paper.json"
            }
        },
        "legislativeTerm": {
            "description": "{{ Body.properties.legislativeTerm.description }}",
            "type": "array",
            "items": {
                "$ref": "LegislativeTerm.json"
            }
        },
        "agendaItem": {
            "description": "{{ Body.properties.agendaItem.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "AgendaItem.json"
            }
        },
        "consultation": {
            "description": "{{ Body.properties.consultation.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Consultation.json"
            }
        },
        "file": {
            "description": "{{ Body.properties.file.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "File.json"
            }
        },
        "locationList": {
            "description": "{{ Body.properties.locationList.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Location.json"
            }
        },
        "legislativeTermList": {
            "description": "{{ Body.properties.legislativeTermList.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "LegislativeTerm.json"
            }
        },
        "membership": {
            "description": "{{ Body.properties.membership.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "$ref": "Membership.json"
            }
        },
        "classification": {
            "description": "{{ Body.properties.classification.description }}",
            "type": "string"
        },
        "location": {
            "description": "{{ Body.properties.location.description }}",
            "$ref": "Location.json"
        },
        "mainOrganization": {
            "description": "{{ Body.properties.mainOrganization.description }}",
            "type": "string",
            "format": "url",
            "$ref": "Organization",
            "references": "Organization",
            "cardinality": "1:1"
        },
        "keyword": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "created": {
            "type": "string",
            "format": "date-time"
        },
        "modified": {
            "type": "string",
            "format": "date-time"
        },
        "web": {
            "type": "string",
            "format": "url"
        },
        "deleted": {
            "type": "boolean"
        }
    }
}

=== OParl/spec/examples/Body-01.json
{
    "$schema": "https://schema.oparl.org/1.1/Body",
    "id": "https://oparl.example.org/body/0",
    "type": "https://schema.oparl.org/1.1/Body",
    "system": "https://oparl.example.org/",
    "contactEmail": "ris@beispielstadt.de",
    "contactName": "RIS-Betreuung",
    "ags": "05315000",
    "rgs": "053150000000",
    "equivalent": [
        "http://d-nb.info/gnd/2015732-0",
        "http://dbpedia.org/resource/Cologne"
    ],
    "shortName": "Köln",
    "name": "Stadt Köln, kreisfreie Stadt",
    "website": "http://www.beispielstadt.de/",
    "license": "http://creativecommons.org/licenses/by/4.0/",
    "licenseValidSince": "2014-01-01T00:00:00+02:00",
    "organization": "https://oparl.example.org/body/0/organizations/",
    "person": "https://oparl.example.org/body/0/persons/",
    "meeting": "https://oparl.example.org/body/0/meetings/",
    "paper": "https://oparl.example.org/body/0/papers/",
    "agendaItem": "https://oparl.example.org/body/0/agendaItems/",
    "consultation": "https://oparl.example.org/body/0/consultations/",
    "file": "https://oparl.example.org/body/0/files/",
    "locationList": "https://oparl.example.org/body/0/locations/",
    "membership": "https://oparl.example.org/body/0/memberships/",
    "legislativeTerm": [
        {
            "id": "https://oparl.example.org/term/21",
            "type": "https://schema.oparl.org/1.1/LegislativeTerm",
            "body": "https://oparl.example.org/body/0",
            "name": "21. Wahlperiode",
            "startDate": "2010-12-03",
            "endDate": "2013-12-03",
            "created": "2014-01-08T14:28:31+01:00",
            "modified": "2014-01-08T14:28:31+01:00"
        }
    ],
    "location": {
        "id": "https://oparl.example.org/location/0",
        "type": "https://schema.oparl.org/1.1/Location",
        "description": "Rathaus der Beispielstadt, Ratshausplatz 1, 12345 Beispielstadt",
        "created": "2014-01-08T14:28:31+01:00",
        "modified": "2014-01-08T14:28:31+01:00",
        "geojson": {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    50.1234,
                    10.4321
                ]
            },
            "properties": {
                "name": "Rathausplatz"
            }
        }
    },
    "classification": "Kreisfreie Stadt",
    "created": "2014-01-08T14:28:31+01:00",
    "modified": "2014-01-08T14:28:31+01:00"
}
