=== OParl/spec/schema/Location.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/Location",
    "title": "Location",
    "description": "{{ Location.description }}",
    "type": "object",
    "required": [
        "id",
        "type"
    ],
    "properties": {
        "id": {
            "type": "string",
            "format": "url"
        },
        "type": {
            "type": "string",
            "const": "https://schema.oparl.org/1.1/Location"
        },
        "description": {
            "description": "{{ Location.properties.description.description }}",
            "type": "string"
        },
        "geojson": {
            "description": "{{ Location.properties.geojson.description }}",
            "type": "object"
        },
        "streetAddress": {
            "description": "{{ Location.properties.streetAddress.description }}",
            "type": "string"
        },
        "room": {
            "description": "{{ Location.properties.room.description }}",
            "type": "string"
        },
        "postalCode": {
            "description": "{{ Location.properties.postalCode.description }}",
            "type": "string"
        },
        "subLocality": {
            "description": "{{ Location.properties.subLocality.description }}",
            "type": "string"
        },
        "locality": {
            "description": "{{ Location.properties.locality.description }}",
            "type": "string"
        },
        "bodies": {
            "description": "{{ Location.properties.bodies.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url",
                "references": "Body"
            }
        },
        "organizations": {
            "description": "{{ Location.properties.organizations.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url",
                "references": "Organization"
            }
        },
        "persons": {
            "description": "{{ Location.properties.persons.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url",
                "references": "Person"
            }
        },
        "meetings": {
            "description": "{{ Location.properties.meetings.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url",
                "references": "Meeting"
            }
        },
        "papers": {
            "description": "{{ Location.properties.papers.description }}",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url",
                "references": "Paper"
            }
        },
        "license": {
            "type": "string"
        },
        "keyword": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "created": {
            "type": "string",
            "format": "date-time"
        },
        "modified": {
            "type": "string",
            "format": "date-time"
        },
        "web": {
            "type": "string",
            "format": "url"
        },
        "deleted": {
            "type": "boolean"
        }
    }
}

=== OParl/spec/examples/Location-01.json
{
    "$schema": "https://schema.oparl.org/1.1/Location",
    "id": "https://oparl.example.org/location/0",
    "type": "https://schema.oparl.org/1.1/Location",
    "description": "Deutscher Bundestag, Platz der Republik 1, 11011 Berlin",
    "streetAddress": "Platz der Republik 1",
    "postalCode": "11011",
    "locality": "Berlin",
    "room": "Plenarsaal",
    "geojson": {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [
                52.518855,
                13.376198
            ]
        },
        "properties": {
            "name": "Reichstagsgeb√§ude"
        }
    }
}
