=== OParl/spec/schema/Meeting.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/Meeting",
    "title": "Meeting",
    "description": "{{ Meeting.description }}",
    "type": "object",
    "required": [
        "id",
        "type"
    ],
    "properties": {
        "id": {
            "type": "string",
            "format": "url"
        },
        "type": {
            "type": "string",
            "const": "https://schema.oparl.org/1.1/Meeting"
        },
        "name": {
            "description": "{{ Meeting.properties.name.description }}",
            "type": "string"
        },
        "meetingState": {
            "description": "{{ Meeting.properties.meetingState.description }}",
            "type": "string"
        },
        "cancelled": {
            "description": "{{ Meeting.properties.cancelled.description }}",
            "type": "boolean"
        },
        "start": {
            "description": "{{ Meeting.properties.start.description }}",
            "type": "string",
            "format": "date-time"
        },
        "end": {
            "description": "{{ Meeting.properties.end.description }}",
            "type": "string",
            "format": "date-time"
        },
        "location": {
            "description": "{{ Meeting.properties.location.description }}",
            "$ref": "Location.json"
        },
        "organization": {
            "description": "{{ Meeting.properties.organization.description }}",
            "references": "Organization",
            "backreference": "meeting",
            "cardinality": "n:m",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url"
            }
        },
        "participant": {
            "description": "{{ Meeting.properties.participant.description }}",
            "references": "Person",
            "cardinality": "n:m",
            "type": "array",
            "items": {
                "type": "string",
                "format": "url"
            }
        },
        "invitation": {
            "description": "{{ Meeting.properties.invitation.description }}",
            "$ref": "File.json"
        },
        "resultsProtocol": {
            "description": "{{ Meeting.properties.resultsProtocol.description }}",
            "$ref": "File.json"
        },
        "verbatimProtocol": {
            "description": "{{ Meeting.properties.verbatimProtocol.description }}",
            "$ref": "File.json"
        },
        "auxiliaryFile": {
            "description": "{{ Meeting.properties.auxiliaryFile.description }}",
            "type": "array",
            "items": {
                "$ref": "File.json"
            }
        },
        "agendaItem": {
            "description": "{{ Meeting.properties.agendaItem.description }}",
            "type": "array",
            "items": {
                "$ref": "AgendaItem.json"
            }
        },
        "license": {
            "type": "string"
        },
        "keyword": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "created": {
            "type": "string",
            "format": "date-time"
        },
        "modified": {
            "type": "string",
            "format": "date-time"
        },
        "web": {
            "type": "string",
            "format": "url"
        },
        "deleted": {
            "type": "boolean"
        }
    }
}

=== OParl/spec/examples/Meeting-01.json
{
    "$schema": "https://schema.oparl.org/1.1/Meeting",
    "id": "https://oparl.example.org/meeting/281",
    "type": "https://schema.oparl.org/1.1/Meeting",
    "name": "4. Sitzung des Finanzausschusses",
    "start": "2013-01-04T08:00:00+01:00",
    "end": "2013-01-04T12:00:00+01:00",
    "location": {
        "id": "https://oparl.example.org/location/0",
        "type": "https://schema.oparl.org/1.1/Location",
        "description": "Rathaus der Beispielstadt, Ratshausplatz 1, 12345 Beispielstadt",
        "created": "2012-01-06T12:01:00+01:00",
        "modified": "2012-01-08T14:05:27+01:00",
        "geojson": {
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [
                    50.1234,
                    10.4321
                ]
            },
            "properties": {
                "name": "Rathausplatz"
            }
        }
    },
    "organization": [
        "https://oparl.example.org/organization/34"
    ],
    "invitation": {
        "id": "https://oparl.example.org/files/57739",
        "type": "https://schema.oparl.org/1.1/File",
        "name": "Einladung",
        "fileName": "einladung.pdf",
        "mimeType": "application/pdf",
        "date": "2012-01-08",
        "modified": "2012-01-08T14:05:27+01:00",
        "sha1Checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 82930,
        "accessUrl": "https://oparl.example.org/files/57739.pdf",
        "downloadUrl": "https://oparl.example.org/files/download/57739.pdf",
        "created": "2012-01-06T12:01:00+01:00"
    },
    "resultsProtocol": {
        "id": "https://oparl.example.org/files/57739",
        "type": "https://schema.oparl.org/1.1/File",
        "name": "Protokoll",
        "fileName": "protokoll.pdf",
        "mimeType": "application/pdf",
        "date": "2012-01-08",
        "sha1Checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 82930,
        "accessUrl": "https://oparl.example.org/files/57739.pdf",
        "downloadUrl": "https://oparl.example.org/files/download/57739.pdf",
        "modified": "2012-01-08T14:05:27+01:00",
        "created": "2012-01-06T12:01:00+01:00"
    },
    "verbatimProtocol": {
        "id": "https://oparl.example.org/files/57739",
        "type": "https://schema.oparl.org/1.1/File",
        "name": "Wortprotokoll",
        "fileName": "wortprotokoll.pdf",
        "mimeType": "application/pdf",
        "date": "2012-01-08",
        "sha1Checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
        "size": 82930,
        "accessUrl": "https://oparl.example.org/files/57739.pdf",
        "downloadUrl": "https://oparl.example.org/files/download/57739.pdf",
        "modified": "2012-01-08T14:05:27+01:00",
        "created": "2012-01-08T14:05:27+01:00"
    },
    "auxiliaryFile": [
        {
            "id": "https://oparl.example.org/files/57739",
            "type": "https://schema.oparl.org/1.1/File",
            "name": "Nachtrags-Tagesordnung",
            "fileName": "nachtrag-TO.pdf",
            "mimeType": "application/pdf",
            "date": "2012-01-08",
            "sha1Checksum": "da39a3ee5e6b4b0d3255bfef95601890afd80709",
            "size": 82930,
            "accessUrl": "https://oparl.example.org/files/57739.pdf",
            "downloadUrl": "https://oparl.example.org/files/download/57739.pdf",
            "modified": "2012-01-08T14:05:27+01:00",
            "created": "2012-01-08T14:05:27+01:00"
        }
    ],
    "agendaItem": [
        {
            "id": "https://oparl.example.org/agendaitem/3271",
            "type": "https://schema.oparl.org/1.1/AgendaItem",
            "meeting": "https://oparl.example.org/meeting/281",
            "number": "10.1",
            "name": "Satzungsänderung für Ausschreibungen",
            "public": true,
            "consultation": "https://oparl.example.org/consultation/1034",
            "result": "Geändert beschlossen",
            "resolutionText": "Der Beschluss weicht wie folgt vom Antrag ab: ...",
            "created": "2012-01-06T12:01:00+01:00",
            "modified": "2012-01-08T14:05:27+01:00"
        }
    ],
    "created": "2012-01-06T12:01:00+01:00",
    "modified": "2012-01-08T14:05:27+01:00"
}
