=== OParl/spec/schema/Person.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/Person",
    "title": "Person",
    "description": "{{ Person.description }}",
    "type": "object",
    "required": [
        "id",
        "type"
    ],
    "properties": {
        "id": {
            "type": "string",
            "format": "url"
        },
        "type": {
            "type": "string",
            "const": "https://schema.oparl.org/1.1/Person"
        },
        "body": {
            "description": "{{ Person.properties.body.description }}",
            "references": "Body",
            "backreference": "person",
            "cardinality": "n:1",
            "type": "string",
            "format": "url"
        },
        "name": {
            "description": "{{ Person.properties.name.description }}",
            "type": "string"
        },
        "familyName": {
            "description": "{{ Person.properties.familyName.description }}",
            "type": "string"
        },
        "givenName": {
            "description": "{{ Person.properties.givenName.description }}",
            "type": "string"
        },
        "formOfAddress": {
            "description": "{{ Person.properties.formOfAddress.description }}",
            "type": "string"
        },
        "affix": {
            "description": "{{ Person.properties.affix.description }}",
            "type": "string"
        },
        "title": {
            "description": "{{ Person.properties.title.description }}",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "gender": {
            "description": "{{ Person.properties.gender.description }}",
            "type": "string"
        },
        "phone": {
            "description": "{{ Person.properties.phone.description }}",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "email": {
            "description": "{{ Person.properties.email.description }}",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "location": {
            "description": "{{ Person.properties.location.description }}",
            "references": "Location",
            "backreference": "person",
            "cardinality": "n:1",
            "type": "string",
            "format": "url"
        },
        "locationObject": {
            "description": "{{ Person.properties.locationObject.description }}",
            "type": "object",
            "schema": "Location.json"
        },
        "status": {
            "description": "{{ Person.properties.status.description }}",
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "membership": {
            "description": "{{ Person.properties.membership.description }}",
            "type": "array",
            "items": {
                "type": "object",
                "schema": "Membership.json"
            }
        },
        "image": {
            "description": "{{ Person.properties.image.description }}",
            "type": "object",
            "schema": "File.json"
        },
        "life": {
            "description": "{{ Person.properties.life.description }}",
            "type": "string"
        },
        "lifeSource": {
            "description": "{{ Person.properties.lifeSource.description }}",
            "type": "string"
        },
        "license": {
            "type": "string"
        },
        "keyword": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "created": {
            "type": "string",
            "format": "date-time"
        },
        "modified": {
            "type": "string",
            "format": "date-time"
        },
        "web": {
            "type": "string",
            "format": "url"
        },
        "deleted": {
            "type": "boolean"
        }
    }
}

=== OParl/spec/examples/Person-01.json
{
    "$schema": "https://schema.oparl.org/1.1/Person",
    "id": "https://oparl.example.org/person/29",
    "type": "https://schema.oparl.org/1.1/Person",
    "body": "https://oparl.example.org/body/0",
    "name": "Prof. Dr. Max Mustermann",
    "familyName": "Mustermann",
    "givenName": "Max",
    "title": [
        "Prof.",
        "Dr."
    ],
    "formOfAddress": "Ratsfrau",
    "gender": "male",
    "email": [
        "max@mustermann.de"
    ],
    "phone": [
        "+493012345678"
    ],
    "status": [
        "Bezirksbürgermeister"
    ],
    "membership": [
        {
            "id": "https://oparl.example.org/memberships/385",
            "type": "https://schema.oparl.org/1.1/Membership",
            "organization": "https://oparl.example.org/organizations/5",
            "role": "Vorsitzende",
            "votingRight": true,
            "startDate": "2013-12-03",
            "created": "2011-11-11T11:11:00+01:00",
            "modified": "2012-08-16T14:05:27+02:00"
        },
        {
            "id": "https://oparl.example.org/memberships/693",
            "type": "https://schema.oparl.org/1.1/Membership",
            "organization": "https://oparl.example.org/organizations/9",
            "role": "Sachkundige Bürgerin",
            "votingRight": false,
            "startDate": "2013-12-03",
            "endDate": "2014-07-28",
            "created": "2011-11-11T11:11:00+01:00",
            "modified": "2012-08-16T14:05:27+02:00"
        }
    ],
    "created": "2011-11-11T11:11:00+01:00",
    "modified": "2012-08-16T14:05:27+02:00"
}
