=== OParl/spec/schema/System.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/System",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "https://schema.oparl.org/1.1/System",
    "title": "System",
    "description": "{{ System.description }}",
    "type": "object",
    "required": [
        "id",
        "type",
        "oparlVersion",
        "body"
    ],
    "properties": {
        "id": {
            "type": "string",
            "format": "url"
        },
        "type": {
            "type": "string",
            "const": "https://schema.oparl.org/1.1/System"
        },
        "oparlVersion": {
            "type": "string",
            "enum": ["https://schema.oparl.org/1.0/", "https://schema.oparl.org/1.1/"],
            "description": "{{ System.properties.oparlVersion.description }}"
        },
        "otherOparlVersions": {
            "description": "{{ System.properties.otherOparlVersions.description }}",
            "references": "System",
            "items": {
                "type": "string",
                "format": "url"
            },
            "type": "array"
        },
        "license": {
            "description": "{{ System.properties.license.description }}",
            "type": "string",
            "format": "url"
        },
        "body": {
            "description": "{{ System.properties.body.description }}",
            "type": "string",
            "format": "url",
            "references": "externalList",
            "items": {
                "type": "object",
                "schema": "Body.json"
            }
        },
        "name": {
            "description": "{{ System.properties.name.description }}",
            "type": "string"
        },
        "contactEmail": {
            "description": "{{ System.properties.contactEmail.description }}",
            "type": "string"
        },
        "contactName": {
            "description": "{{ System.properties.contactName.description }}",
            "type": "string"
        },
        "website": {
            "description": "{{ System.properties.website.description }}",
            "type": "string",
            "format": "url"
        },
        "vendor": {
            "description": "{{ System.properties.vendor.description }}",
            "type": "string",
            "format": "url"
        },
        "product": {
            "description": "{{ System.properties.product.description }}",
            "type": "string",
            "format": "url"
        },
        "created": {
            "type": "string",
            "format": "date-time"
        },
        "modified": {
            "type": "string",
            "format": "date-time"
        },
        "web": {
            "type": "string",
            "format": "url"
        },
        "deleted": {
            "type": "boolean"
        }
    }
}

=== OParl/spec/examples/System-01.json
{
    "$schema": "https://schema.oparl.org/1.1/System",
    "id": "https://oparl.example.org/",
    "type": "https://schema.oparl.org/1.1/System",
    "oparlVersion": "https://schema.oparl.org/1.1/",
    "body": "https://oparl.example.org/bodies",
    "name": "Beispiel-System",
    "contactEmail": "info@example.org",
    "contactName": "Allgemeiner OParl Kontakt",
    "website": "http://www.example.org/",
    "vendor": "http://example-software.com/",
    "product": "http://example-software.com/oparl-server/",
    "otherOparlVersions": [
        "https://oparl2.example.org/"
    ],
    "created": "2011-11-11T11:11:00+01:00",
    "modified": "2012-11-11T11:11:00+01:00"
}
